# Generated by Django 5.2.8 on 2026-01-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('user_photo', models.ImageField(upload_to='captures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
