# Generated by Django 5.2.8 on 2026-01-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="device_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
